# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-21 04:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['pk'], 'verbose_name': 'Block', 'verbose_name_plural': 'Blocks'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['pk'], 'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='Name'),
        ),
    ]
