# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-20 15:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.UUIDField(default=uuid.UUID('4996fd31-93c4-4d60-ab59-0d85ef40f165'))),
                ('state', models.IntegerField(choices=[(0, 'OFFLINE'), (1, 'ONLINE'), (2, 'READY TO PLAY'), (3, 'IN GAME')], default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
