# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-20 16:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.PositiveIntegerField(default=0, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('52d0e4a6-610d-43e6-a634-4ba5999f8be3'), verbose_name='UUID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.IntegerField(choices=[(0, 'OFFLINE'), (1, 'ONLINE'), (2, 'READY TO PLAY'), (3, 'IN GAME')], default=0, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
