# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-21 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial_squashed_0007_auto_20190421_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('b9437ddc-48ce-4edc-8711-2c1358828a01'), verbose_name='UUID'),
        ),
    ]
