# Generated by Django 2.2 on 2019-04-21 05:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20190421_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('1d9cadfb-f7c6-4d84-a20f-800091d4119b'), verbose_name='UUID'),
        ),
    ]
