# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-21 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20190421_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('a317abb0-51bc-4308-a072-ae2113c6d947'), verbose_name='UUID'),
        ),
    ]
