# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-20 21:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20190421_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('5986d802-fb1d-4114-b77e-e10c1c062c36'), verbose_name='UUID'),
        ),
    ]
