# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-21 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20190421_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('39157793-29b5-4209-a1a4-21648b9f050d'), verbose_name='UUID'),
        ),
    ]
