# Generated by Django 2.2 on 2019-04-21 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20190421_1037'),
        ('profile', '0004_auto_20190421_1027'),
    ]

    operations = [
    ]
