# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-20 23:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
        ('profile', '0005_auto_20190421_0053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='blocks',
            field=models.ManyToManyField(to='topic.Block', verbose_name='Blocks'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='guid',
            field=models.UUIDField(default=uuid.UUID('92a8336e-4d5e-4336-96e8-292a07b7e911'), verbose_name='UUID'),
        ),
    ]
