# Generated by Django 2.2 on 2019-04-21 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0003_auto_20190421_0854'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_points', models.IntegerField(default=0, null=True, verbose_name='Winner points')),
                ('loser_points', models.IntegerField(default=0, null=True, verbose_name='Loser points')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='Game start time')),
                ('end', models.DateTimeField(verbose_name='Game end time')),
                ('state', models.IntegerField(choices=[(0, 'WAITING FOR PLAYERS'), (1, 'IN GAME BUT FIRST IS ENDED'), (2, 'IN GAME BUT SECOND IS ENDED'), (3, 'IN GAME'), (100, 'GAME IS ENDED')], default=0, verbose_name='State')),
                ('loser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loser_games_set', to='profile.Profile', verbose_name='Loser')),
                ('player1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profile.Profile', verbose_name='Player 1')),
                ('player2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='profile.Profile', verbose_name='Player 2')),
                ('winner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winner_games_set', to='profile.Profile', verbose_name='Winner')),
            ],
            options={
                'verbose_name': 'Game',
                'verbose_name_plural': 'Games',
            },
        ),
    ]
