# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-21 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0002_auto_20190421_0725'),
        ('game', '0002_auto_20190421_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_1', models.BooleanField(verbose_name='Player 1')),
                ('player_2', models.BooleanField(verbose_name='Player 2')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game', verbose_name='Game')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topic.Test', verbose_name='Test')),
            ],
            options={
                'verbose_name': 'Game result',
                'verbose_name_plural': 'Game results',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='results',
            field=models.ManyToManyField(through='game.GameResults', to='topic.Test'),
        ),
    ]
